// <auto-generated />
using System;
using ChameRozAP.ServiceManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChameRozAP.Migrations
{
    [DbContext(typeof(CL_DBcontextAP))]
    [Migration("20251220162939_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("ChameRozAP.ServiceManager.dbChameRoz", b =>
                {
                    b.Property<int>("ChameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChameText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChameID");

                    b.ToTable("ChameRoz");
                });

            modelBuilder.Entity("ChameRozAP.ServiceManager.dbInfoTodayChame", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChameID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("ChameID");

                    b.ToTable("ChameRozToday");
                });

            modelBuilder.Entity("ChameRozAP.ServiceManager.dbInfoTodayChame", b =>
                {
                    b.HasOne("ChameRozAP.ServiceManager.dbChameRoz", "chameRoz")
                        .WithMany()
                        .HasForeignKey("ChameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chameRoz");
                });
#pragma warning restore 612, 618
        }
    }
}
